services:
  php:
    build: './php'
    networks:
      - backend
    volumes:
      - ./html:/usr/share/nginx/html

  nginx:
    image: nginx:alpine
    depends_on:
      - php
      - mariadb
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf.d/
 
  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - dbdata:/var/lib/mysql

networks:
  frontend:
  backend:
volumes:
  dbdata:

